defaults:
  - classifier: svm

aug_n: 19
transforms:
  - class: torchvision.transforms.RandomAffine
    params:
      degrees: 15
  # - class: torchvision.transforms.RandomAffine
  #   params:
  #     degrees: 0
  #     translate: [0.2, 0.2]
  - class: torchvision.transforms.RandomAffine
    params:
      degrees: 0
      scale: [0.8, 1.2]
  - class: torchvision.transforms.ToTensor
  # - class: add_noise.AddDots
  #   params:
  #     n: 10
  #     value: 0
  # - class: add_noise.AddDots
  #   params:
  #     n: 10
  #     value: 1
  - class: add_noise.AddNoise
    params:
      mean: 0
      std: 0.01
  # - class: torchvision.transforms.RandomErasing
  #   params:
  #     p: 0.2
  #     scale: [0.1, 0.1]
  #     ratio: [0.5, 2]
  - class: torchvision.transforms.ToPILImage

seed: 0
